# Generated by Django 3.2.7 on 2021-09-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('catalogNbr', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=100)),
                ('instructorLast', models.CharField(max_length=100)),
                ('instructorFirst', models.CharField(max_length=100)),
                ('aCount', models.CharField(max_length=100)),
                ('bCount', models.CharField(max_length=100)),
                ('cCount', models.CharField(max_length=100)),
                ('dCount', models.CharField(max_length=100)),
                ('fCount', models.CharField(max_length=100)),
                ('satisfactory', models.CharField(max_length=100)),
                ('dropCount', models.CharField(max_length=100)),
                ('percentA', models.CharField(max_length=100)),
            ],
        ),
    ]
